/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 */
// const LCAPApplicationService = require('@sap/low-code-event-handler');
// const create_Logic = require('./code/create-logic');

// const { data } = require("hdb/lib/protocol");

const cds = require("@sap/cds");

// class demoprService extends LCAPApplicationService {
//     async init() {

//         this.before('CREATE', 'PurchaseOrders', async (request) => {
//             // await create_Logic({
//             //     request
//             // });
//             data = request.data;
//             data.RequestId = 'PR009';
//         });

//         return super.init();
//     }
// }


// module.exports = {
//     demoprService
// };

module.exports = cds.service.impl(async function () {
    const { PurchaseOrders } = this.entities;
    this.before("CREATE", PurchaseOrders, (request) => {
        data = request.data;
        data.RequestId = 'PR009';
    });
});