/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const create_Logic = require('./code/create-logic');

class demoprService extends LCAPApplicationService {
    async init() {

        this.before('CREATE', 'PurchaseOrders', async (request) => {
            await create_Logic({
                request
            });
        });

        return super.init();
    }
}


module.exports = {
    demoprService
};