/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 */
// const LCAPApplicationService = require('@sap/low-code-event-handler');
// const requestid_Logic = require('./code/requestid-logic');

// class demoprService extends LCAPApplicationService {
//     async init() {

//         this.before('CREATE', 'PurchaseOrders', async (request) => {
//             await requestid_Logic({
//                 request
//             });
//         });

//         return super.init();
//     }
// }


// module.exports = {
//     demoprService
// };

const cds = require("@sap/cds");
// const { data } = require("hdb/lib/protocol");

module.exports = cds.service.impl(async function () {
    const { PurchaseOrders } = this.entities;
    this.before("CREATE", PurchaseOrders, (request) => {

        console.log(request);
        data = request.data;
        data.RequestId = 'PR'+Math.floor((Math.random()*100000) + 1);
        data.Status = 'New';
    });
});